"""
db.py  —  Shared database utilities for GADMS Dashboard
Persistent DuckDB — no external database required.
"""
import re
from pathlib import Path
import pandas as pd
import streamlit as st

SQL_FILE = Path(__file__).parent / "TEAM_ALPHA.sql"
DB_FILE  = Path(__file__).parent / "gadms_v2.duckdb"   # new name forces fresh build


@st.cache_resource(show_spinner="Loading GADMS database...")
def get_connection():
    import duckdb

    # Delete any old/corrupt DB files from previous attempts
    for old in Path(__file__).parent.glob("gadms*.duckdb"):
        if old.name != DB_FILE.name:
            try:
                old.unlink()
            except Exception:
                pass

    first_run = not DB_FILE.exists()
    con = duckdb.connect(str(DB_FILE))

    try:
        con.execute("SET preserve_identifier_case = false")
    except Exception:
        pass

    if first_run:
        _load_sql(con, SQL_FILE)
    else:
        # Health check — rebuild if tables are missing
        try:
            count = con.execute("SELECT COUNT(*) FROM Programme").fetchone()[0]
            if count == 0:
                raise Exception("empty")
        except Exception:
            con.close()
            try:
                DB_FILE.unlink()
            except Exception:
                pass
            con = duckdb.connect(str(DB_FILE))
            try:
                con.execute("SET preserve_identifier_case = false")
            except Exception:
                pass
            _load_sql(con, SQL_FILE)

    return con


def _load_sql(con, sql_path: Path):
    if not sql_path.exists():
        st.error(f"SQL file not found: {sql_path}")
        st.stop()

    raw = sql_path.read_text()
    t = raw.replace("SET client_min_messages = WARNING;", "")
    t = re.sub(r"SELECT setval\([^;]*\);", "", t)
    t = re.sub(r'\bBIGSERIAL\s+PRIMARY\s+KEY\b',
               'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY', t)
    t = re.sub(r'\bSERIAL\s+PRIMARY\s+KEY\b',
               'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY', t)

    buff, stmts = [], []
    for line in t.split("\n"):
        buff.append(line)
        if line.strip().endswith(";"):
            stmts.append("\n".join(buff))
            buff = []

    c = {"e": 0, "a": 0, "f": 0, "l": 0}
    ok_count = 0
    for st_ in stmts:
        s = st_
        lines = s.split("\n")
        while lines and (lines[0].strip().startswith("--") or not lines[0].strip()):
            lines.pop(0)
        s = "\n".join(lines).strip()
        if not s:
            continue
        if s.startswith("INSERT INTO Enrollment "):
            c["e"] += 1
            s = s.replace("(StudentID,", "(EnrollmentID, StudentID,")
            s = s.replace(") VALUES (", f") VALUES ({c['e']}, ", 1)
        elif s.startswith("INSERT INTO AssessmentResult "):
            c["a"] += 1
            s = s.replace("(EnrollmentID,", "(ResultID, EnrollmentID,")
            s = s.replace(") VALUES (", f") VALUES ({c['a']}, ", 1)
        elif s.startswith("INSERT INTO FeePayment "):
            c["f"] += 1
            s = s.replace("(StudentID,", "(PaymentID, StudentID,")
            s = s.replace(") VALUES (", f") VALUES ({c['f']}, ", 1)
        elif s.startswith("INSERT INTO LMSActivity "):
            c["l"] += 1
            s = s.replace("(StudentID,", "(ActivityID, StudentID,")
            s = s.replace(") VALUES (", f") VALUES ({c['l']}, ", 1)
        try:
            con.execute(s)
            ok_count += 1
        except Exception:
            pass

    _reset_sequences(con)
    return ok_count


def _reset_sequences(con):
    tables = {
        "Department": "DepartmentID",       "Programme": "ProgrammeID",
        "Course": "CourseID",               "Semester": "SemesterID",
        "Admission": "AdmissionID",         "CourseOffering": "CourseOfferingID",
        "Enrollment": "EnrollmentID",       "AssessmentResult": "ResultID",
        "FeePayment": "PaymentID",          "LMSActivity": "ActivityID",
    }
    for tbl, col in tables.items():
        try:
            row = con.execute(f"SELECT COALESCE(MAX({col}),0)+1 FROM {tbl}").fetchone()
            con.execute(f"ALTER TABLE {tbl} ALTER COLUMN {col} RESTART WITH {int(row[0])}")
        except Exception:
            pass


_COL_MAP: dict[str, str] = {
    'departmentid': 'DepartmentID',        'departmentname': 'DepartmentName',
    'faculty': 'Faculty',                   'officelocation': 'OfficeLocation',
    'programmeid': 'ProgrammeID',           'programmecode': 'ProgrammeCode',
    'programmename': 'ProgrammeName',       'degreetype': 'DegreeType',
    'durationyears': 'DurationYears',
    'courseid': 'CourseID',                 'coursecode': 'CourseCode',
    'coursetitle': 'CourseTitle',           'credithours': 'CreditHours',
    'lecturerid': 'LecturerID',             'lecturername': 'LecturerName',
    'rank': 'Rank',                         'email': 'Email',
    'semesterid': 'SemesterID',             'semestername': 'SemesterName',
    'startdate': 'StartDate',               'enddate': 'EndDate',
    'studentid': 'StudentID',               'firstname': 'FirstName',
    'lastname': 'LastName',                 'gender': 'Gender',
    'dateofbirth': 'DateOfBirth',           'phonenumber': 'PhoneNumber',
    'admissionyear': 'AdmissionYear',       'status': 'Status',
    'admissionid': 'AdmissionID',           'applicantname': 'ApplicantName',
    'admissiondate': 'AdmissionDate',       'admissionstatus': 'AdmissionStatus',
    'courseofferingid': 'CourseOfferingID', 'academicyear': 'AcademicYear',
    'enrollmentid': 'EnrollmentID',         'enrollmentdate': 'EnrollmentDate',
    'enrollmentstatus': 'EnrollmentStatus',
    'resultid': 'ResultID',                 'courseworkscore': 'CourseworkScore',
    'examscore': 'ExamScore',               'finalgrade': 'FinalGrade',
    'paymentid': 'PaymentID',               'amountpaid': 'AmountPaid',
    'paymentdate': 'PaymentDate',           'paymentmethod': 'PaymentMethod',
    'balance': 'Balance',
    'activityid': 'ActivityID',             'logintimestamp': 'LoginTimestamp',
    'activitytype': 'ActivityType',         'durationminutes': 'DurationMinutes',
    'students': 'Students',                 'enrollments': 'Enrollments',
    'results': 'Results',                   'events': 'Events',
    'minutes': 'Minutes',                   'total': 'Total',
    'payments': 'Payments',                 'paid': 'Paid',
    'outstanding': 'Outstanding',           'count': 'Count',
    'fullname': 'FullName',                 'coursename': 'CourseName',
    'grade': 'Grade',                       'avgmark': 'AvgMark',
    'totalpaid': 'TotalPaid',               'totalbalance': 'TotalBalance',
    'numpayments': 'NumPayments',           'numsections': 'NumSections',
    'n': 'n',                               'label': 'label',
    'studentname': 'StudentName',
}


def _fix_columns(df: pd.DataFrame) -> pd.DataFrame:
    df.columns = [_COL_MAP.get(c.lower(), c) for c in df.columns]
    return df


@st.cache_data(ttl=5, show_spinner=False)
def q(sql: str) -> pd.DataFrame:
    con = get_connection()
    df = con.execute(sql).fetchdf()
    return _fix_columns(df)


def run_write(sql: str) -> None:
    con = get_connection()
    con.execute(sql)
    q.clear()


def is_postgres() -> bool:
    return False
