"""
db.py  —  Shared database utilities for GADMS Dashboard
=========================================================
Imported by both app.py (dashboard) and pages/2_Admin.py (admin backend).
Using a single module ensures both pages share the SAME @st.cache_resource
connection, so admin writes are instantly visible on the dashboard.
"""
import os
import re
from pathlib import Path
import pandas as pd
import streamlit as st

SQL_FILE = Path(__file__).parent / "TEAM_ALPHA.sql"


def _get_pg_url():
    """Look for a Postgres URL in Streamlit secrets or environment."""
    try:
        url = st.secrets.get("DATABASE_URL")
        if url:
            return str(url).strip()
    except Exception:
        pass
    return os.environ.get("DATABASE_URL", "").strip() or None


@st.cache_resource(show_spinner="Connecting to database...")
def get_connection():
    """Return (kind, connection). Postgres if DATABASE_URL is set, else DuckDB."""
    pg_url = _get_pg_url()
    if pg_url:
        from sqlalchemy import create_engine
        # Always normalise to postgresql:// — psycopg2 requires this
        url = pg_url.replace("postgres://", "postgresql://", 1)
        engine = create_engine(
            url,
            pool_pre_ping=True,
            pool_size=2,
            max_overflow=3,
            pool_timeout=30,
            pool_recycle=300,
            connect_args={"sslmode": "require", "connect_timeout": 15},
        )
        return "postgres", engine

    # Fallback: in-memory DuckDB loaded from TEAM_ALPHA.sql
    import duckdb
    con = duckdb.connect(":memory:")
    _load_sql_into_duckdb(con, SQL_FILE)
    return "duckdb", con


def _load_sql_into_duckdb(con, sql_path: Path):
    """Translate Postgres-specific syntax and execute the GADMS script in DuckDB."""
    if not sql_path.exists():
        st.error(f"SQL file not found: {sql_path}")
        st.stop()

    raw = sql_path.read_text()
    t = raw.replace("SET client_min_messages = WARNING;", "")
    t = re.sub(r"SELECT setval\([^;]*\);", "", t)

    t = re.sub(
        r'\bBIGSERIAL\s+PRIMARY\s+KEY\b',
        'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY', t
    )
    t = re.sub(
        r'\bSERIAL\s+PRIMARY\s+KEY\b',
        'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY', t
    )

    buff, stmts = [], []
    for line in t.split("\n"):
        buff.append(line)
        if line.strip().endswith(";"):
            stmts.append("\n".join(buff))
            buff = []

    c = {"e": 0, "a": 0, "f": 0, "l": 0}
    for st_ in stmts:
        s = st_
        lines = s.split("\n")
        while lines and (lines[0].strip().startswith("--") or not lines[0].strip()):
            lines.pop(0)
        s = "\n".join(lines).strip()
        if not s:
            continue
        if s.startswith("INSERT INTO Enrollment "):
            c["e"] += 1
            s = s.replace("(StudentID,", "(EnrollmentID, StudentID,")
            s = s.replace(") VALUES (", f") VALUES ({c['e']}, ", 1)
        elif s.startswith("INSERT INTO AssessmentResult "):
            c["a"] += 1
            s = s.replace("(EnrollmentID,", "(ResultID, EnrollmentID,")
            s = s.replace(") VALUES (", f") VALUES ({c['a']}, ", 1)
        elif s.startswith("INSERT INTO FeePayment "):
            c["f"] += 1
            s = s.replace("(StudentID,", "(PaymentID, StudentID,")
            s = s.replace(") VALUES (", f") VALUES ({c['f']}, ", 1)
        elif s.startswith("INSERT INTO LMSActivity "):
            c["l"] += 1
            s = s.replace("(StudentID,", "(ActivityID, StudentID,")
            s = s.replace(") VALUES (", f") VALUES ({c['l']}, ", 1)
        try:
            con.execute(s)
        except Exception:
            pass

    _reset_identity_sequences(con)


def _reset_identity_sequences(con) -> None:
    tables = {
        "Department":       "DepartmentID",
        "Programme":        "ProgrammeID",
        "Course":           "CourseID",
        "Semester":         "SemesterID",
        "Admission":        "AdmissionID",
        "CourseOffering":   "CourseOfferingID",
        "Enrollment":       "EnrollmentID",
        "AssessmentResult": "ResultID",
        "FeePayment":       "PaymentID",
        "LMSActivity":      "ActivityID",
    }
    for tbl, col in tables.items():
        try:
            row = con.execute(
                f"SELECT COALESCE(MAX({col}), 0) + 1 FROM {tbl}"
            ).fetchone()
            next_val = int(row[0])
            con.execute(
                f"ALTER TABLE {tbl} ALTER COLUMN {col} RESTART WITH {next_val}"
            )
        except Exception:
            pass


_COL_MAP: dict[str, str] = {
    'departmentid': 'DepartmentID',       'departmentname': 'DepartmentName',
    'faculty': 'Faculty',                  'officelocation': 'OfficeLocation',
    'programmeid': 'ProgrammeID',          'programmecode': 'ProgrammeCode',
    'programmename': 'ProgrammeName',      'degreetype': 'DegreeType',
    'durationyears': 'DurationYears',
    'courseid': 'CourseID',                'coursecode': 'CourseCode',
    'coursetitle': 'CourseTitle',          'credithours': 'CreditHours',
    'lecturerid': 'LecturerID',            'lecturername': 'LecturerName',
    'rank': 'Rank',                        'email': 'Email',
    'semesterid': 'SemesterID',            'semestername': 'SemesterName',
    'startdate': 'StartDate',              'enddate': 'EndDate',
    'studentid': 'StudentID',              'firstname': 'FirstName',
    'lastname': 'LastName',                'gender': 'Gender',
    'dateofbirth': 'DateOfBirth',          'phonenumber': 'PhoneNumber',
    'admissionyear': 'AdmissionYear',      'status': 'Status',
    'admissionid': 'AdmissionID',          'applicantname': 'ApplicantName',
    'admissiondate': 'AdmissionDate',      'admissionstatus': 'AdmissionStatus',
    'courseofferingid': 'CourseOfferingID','academicyear': 'AcademicYear',
    'enrollmentid': 'EnrollmentID',        'enrollmentdate': 'EnrollmentDate',
    'enrollmentstatus': 'EnrollmentStatus',
    'resultid': 'ResultID',                'courseworkscore': 'CourseworkScore',
    'examscore': 'ExamScore',              'finalgrade': 'FinalGrade',
    'paymentid': 'PaymentID',              'amountpaid': 'AmountPaid',
    'paymentdate': 'PaymentDate',          'paymentmethod': 'PaymentMethod',
    'balance': 'Balance',
    'activityid': 'ActivityID',            'logintimestamp': 'LoginTimestamp',
    'activitytype': 'ActivityType',        'durationminutes': 'DurationMinutes',
    'students': 'Students',                'enrollments': 'Enrollments',
    'results': 'Results',                  'events': 'Events',
    'minutes': 'Minutes',                  'total': 'Total',
    'payments': 'Payments',                'paid': 'Paid',
    'outstanding': 'Outstanding',          'count': 'Count',
    'fullname': 'FullName',                'coursename': 'CourseName',
    'grade': 'Grade',                      'avgmark': 'AvgMark',
    'totalpaid': 'TotalPaid',              'totalbalance': 'TotalBalance',
    'numpayments': 'NumPayments',          'numsections': 'NumSections',
    'n': 'n',                              'label': 'label',
    'studentname': 'StudentName',
}


def _fix_columns(df: pd.DataFrame) -> pd.DataFrame:
    """Rename DataFrame columns to their expected CamelCase form."""
    df.columns = [_COL_MAP.get(c.lower(), c) for c in df.columns]
    return df


@st.cache_data(ttl=30, show_spinner=False)
def q(sql: str) -> pd.DataFrame:
    """
    Execute a read-only SQL query and return a DataFrame with normalised column names.
    Cached for 30 seconds; cleared immediately after any admin write.
    """
    kind, conn = get_connection()
    if kind == "postgres":
        # Must pass a Connection object, NOT the Engine, to pd.read_sql_query
        with conn.connect() as cx:
            df = pd.read_sql_query(sql, cx)
    else:
        df = conn.execute(sql).fetchdf()
    return _fix_columns(df)


def run_write(sql: str) -> None:
    """
    Execute a write operation (INSERT / UPDATE / DELETE).
    Clears the query cache so the dashboard reflects the change immediately.
    """
    kind, conn = get_connection()
    if kind == "postgres":
        from sqlalchemy import text
        with conn.connect() as cx:
            cx.execute(text(sql))
            cx.commit()
    else:
        conn.execute(sql)
    q.clear()


def is_postgres() -> bool:
    return get_connection()[0] == "postgres"
