"""
db.py  —  Shared database utilities for GADMS Dashboard
=========================================================
Imported by both app.py (dashboard) and pages/2_🔐_Admin.py (admin backend).
Using a single module ensures both pages share the SAME @st.cache_resource
connection, so admin writes are instantly visible on the dashboard.
"""
import os
import re
from pathlib import Path
import pandas as pd
import streamlit as st

SQL_FILE = Path(__file__).parent / "TEAM_ALPHA.sql"


def _get_pg_url():
    """Look for a Postgres URL in Streamlit secrets or environment."""
    try:
        url = st.secrets.get("DATABASE_URL")
        if url:
            return url
    except (FileNotFoundError, Exception):
        pass
    return os.environ.get("DATABASE_URL")


@st.cache_resource(show_spinner="Connecting to database…")
def get_connection():
    """Return (kind, connection). Postgres if DATABASE_URL is set, else DuckDB."""
    pg_url = _get_pg_url()
    if pg_url:
        from sqlalchemy import create_engine
        engine = create_engine(pg_url, pool_pre_ping=True)
        return "postgres", engine

    # Fallback: in-memory DuckDB loaded from TEAM_ALPHA.sql
    import duckdb
    con = duckdb.connect(":memory:")
    _load_sql_into_duckdb(con, SQL_FILE)
    return "duckdb", con


def _load_sql_into_duckdb(con, sql_path: Path):
    """Translate Postgres-specific syntax and execute the GADMS script in DuckDB."""
    if not sql_path.exists():
        st.error(f"SQL file not found: {sql_path}")
        st.stop()

    raw = sql_path.read_text()
    t = raw.replace("SET client_min_messages = WARNING;", "")
    t = re.sub(r"SELECT setval\([^;]*\);", "", t)

    # Convert Postgres serial types → DuckDB identity columns.
    # "GENERATED BY DEFAULT AS IDENTITY" allows explicit values (needed during
    # data load below) AND auto-generates values when the column is omitted.
    t = re.sub(
        r'\bBIGSERIAL\s+PRIMARY\s+KEY\b',
        'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY', t
    )
    t = re.sub(
        r'\bSERIAL\s+PRIMARY\s+KEY\b',
        'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY', t
    )

    # split into statements
    buff, stmts = [], []
    for line in t.split("\n"):
        buff.append(line)
        if line.strip().endswith(";"):
            stmts.append("\n".join(buff))
            buff = []

    c = {"e": 0, "a": 0, "f": 0, "l": 0}
    for st_ in stmts:
        s = st_
        lines = s.split("\n")
        while lines and (lines[0].strip().startswith("--") or not lines[0].strip()):
            lines.pop(0)
        s = "\n".join(lines).strip()
        if not s:
            continue
        # Inject explicit serial IDs for the tables that need them
        if s.startswith("INSERT INTO Enrollment "):
            c["e"] += 1
            s = s.replace("(StudentID,", "(EnrollmentID, StudentID,")
            s = s.replace(") VALUES (", f") VALUES ({c['e']}, ", 1)
        elif s.startswith("INSERT INTO AssessmentResult "):
            c["a"] += 1
            s = s.replace("(EnrollmentID,", "(ResultID, EnrollmentID,")
            s = s.replace(") VALUES (", f") VALUES ({c['a']}, ", 1)
        elif s.startswith("INSERT INTO FeePayment "):
            c["f"] += 1
            s = s.replace("(StudentID,", "(PaymentID, StudentID,")
            s = s.replace(") VALUES (", f") VALUES ({c['f']}, ", 1)
        elif s.startswith("INSERT INTO LMSActivity "):
            c["l"] += 1
            s = s.replace("(StudentID,", "(ActivityID, StudentID,")
            s = s.replace(") VALUES (", f") VALUES ({c['l']}, ", 1)
        try:
            con.execute(s)
        except Exception:
            pass  # skip analytics SELECTs at the foot of the file

    # After loading existing data, reset each identity sequence so that new
    # inserts (without explicit IDs) continue from the correct next value.
    _reset_identity_sequences(con)


def _reset_identity_sequences(con) -> None:
    """Advance each identity sequence past the max already-inserted ID."""
    tables = {
        "Department":     "DepartmentID",
        "Programme":      "ProgrammeID",
        "Course":         "CourseID",
        "Semester":       "SemesterID",
        "Admission":      "AdmissionID",
        "CourseOffering": "CourseOfferingID",
        "Enrollment":     "EnrollmentID",
        "AssessmentResult": "ResultID",
        "FeePayment":     "PaymentID",
        "LMSActivity":    "ActivityID",
    }
    for tbl, col in tables.items():
        try:
            row = con.execute(
                f"SELECT COALESCE(MAX({col}), 0) + 1 FROM {tbl}"
            ).fetchone()
            next_val = int(row[0])
            con.execute(
                f"ALTER TABLE {tbl} ALTER COLUMN {col} RESTART WITH {next_val}"
            )
        except Exception:
            pass


# ── Column-name normalisation ─────────────────────────────────────────────────
# PostgreSQL folds all unquoted identifiers to lowercase, so every column name
# comes back lowercase from pd.read_sql_query().  DuckDB preserves the original
# DDL case.  This map converts the lowercase Postgres names back to the
# CamelCase names used throughout the app, and is also applied to DuckDB results
# so that lowercase query aliases (e.g. "AS students") become "Students" in both
# engines.  Keys are always lowercase; values are the expected Python-side names.
_COL_MAP: dict[str, str] = {
    # Schema columns — Department
    'departmentid': 'DepartmentID',       'departmentname': 'DepartmentName',
    'faculty': 'Faculty',                  'officelocation': 'OfficeLocation',
    # Schema columns — Programme
    'programmeid': 'ProgrammeID',          'programmecode': 'ProgrammeCode',
    'programmename': 'ProgrammeName',      'degreetype': 'DegreeType',
    'durationyears': 'DurationYears',
    # Schema columns — Course
    'courseid': 'CourseID',                'coursecode': 'CourseCode',
    'coursetitle': 'CourseTitle',          'credithours': 'CreditHours',
    # Schema columns — Lecturer
    'lecturerid': 'LecturerID',            'lecturername': 'LecturerName',
    'rank': 'Rank',                        'email': 'Email',
    # Schema columns — Semester
    'semesterid': 'SemesterID',            'semestername': 'SemesterName',
    'startdate': 'StartDate',              'enddate': 'EndDate',
    # Schema columns — Student
    'studentid': 'StudentID',              'firstname': 'FirstName',
    'lastname': 'LastName',                'gender': 'Gender',
    'dateofbirth': 'DateOfBirth',          'phonenumber': 'PhoneNumber',
    'admissionyear': 'AdmissionYear',      'status': 'Status',
    # Schema columns — Admission
    'admissionid': 'AdmissionID',          'applicantname': 'ApplicantName',
    'admissiondate': 'AdmissionDate',      'admissionstatus': 'AdmissionStatus',
    # Schema columns — CourseOffering
    'courseofferingid': 'CourseOfferingID','academicyear': 'AcademicYear',
    # Schema columns — Enrollment
    'enrollmentid': 'EnrollmentID',        'enrollmentdate': 'EnrollmentDate',
    'enrollmentstatus': 'EnrollmentStatus',
    # Schema columns — AssessmentResult
    'resultid': 'ResultID',                'courseworkscore': 'CourseworkScore',
    'examscore': 'ExamScore',              'finalgrade': 'FinalGrade',
    # Schema columns — FeePayment
    'paymentid': 'PaymentID',              'amountpaid': 'AmountPaid',
    'paymentdate': 'PaymentDate',          'paymentmethod': 'PaymentMethod',
    'balance': 'Balance',
    # Schema columns — LMSActivity
    'activityid': 'ActivityID',            'logintimestamp': 'LoginTimestamp',
    'activitytype': 'ActivityType',        'durationminutes': 'DurationMinutes',
    # Query aliases used in app.py charts / tables
    'students': 'Students',                'enrollments': 'Enrollments',
    'results': 'Results',                  'events': 'Events',
    'minutes': 'Minutes',                  'total': 'Total',
    'payments': 'Payments',                'paid': 'Paid',
    'outstanding': 'Outstanding',          'count': 'Count',
    'fullname': 'FullName',                'coursename': 'CourseName',
    'grade': 'Grade',                      'avgmark': 'AvgMark',
    # Admin panel aliases
    'totalpaid': 'TotalPaid',              'totalbalance': 'TotalBalance',
    'numpayments': 'NumPayments',          'numsections': 'NumSections',
}


def _fix_columns(df: pd.DataFrame) -> pd.DataFrame:
    """Rename DataFrame columns to their expected CamelCase form."""
    df.columns = [_COL_MAP.get(c.lower(), c) for c in df.columns]
    return df


@st.cache_data(ttl=30, show_spinner=False)
def q(sql: str) -> pd.DataFrame:
    """
    Execute a read-only SQL query and return a DataFrame with normalised column names.
    Cached for 30 seconds; cleared immediately after any admin write.
    """
    kind, conn = get_connection()
    if kind == "postgres":
        df = pd.read_sql_query(sql, conn)
    else:
        df = conn.execute(sql).fetchdf()
    return _fix_columns(df)


def run_write(sql: str) -> None:
    """
    Execute a write operation (INSERT / UPDATE / DELETE).
    Clears the query cache so the dashboard reflects the change on the next load.
    """
    kind, conn = get_connection()
    if kind == "postgres":
        from sqlalchemy import text
        with conn.connect() as c:
            c.execute(text(sql))
            c.commit()
    else:
        conn.execute(sql)
    # Bust the read-query cache immediately
    q.clear()


def is_postgres() -> bool:
    return get_connection()[0] == "postgres"
